### ISSUE TITLE
Code examples

### ISSUE THREAD

**Issue by chrisbuttery** [knowthen/episode-8-serving-content-in-koajs-with-marko#1]
Hi there, I've just added the code examples for episodes [3](https://github.com/chrisbuttery/episode-3-koajs-quickstart-guide), [4](https://github.com/chrisbuttery/episode-4-writing-middleware-in-koajs) and [5](https://github.com/chrisbuttery/episode-5-creating-models-in-koajs) if you want to fork or reference them.

They may be helpful to someone.

Thanks

**Comment by knowthen** [comment]
Chris, thanks for the offer.  I have all the code, just need to find a few
minutes to glance over it and publish.  Should get to it soon.

Best,
James

**Comment by chrisbuttery** [comment]
No problem. Thanks for doing these screencasts
